// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: logstore.proto

package logStore

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Loglevel int32

const (
	Loglevel_warn     Loglevel = 0
	Loglevel_error    Loglevel = 1
	Loglevel_critical Loglevel = 2
)

// Enum value maps for Loglevel.
var (
	Loglevel_name = map[int32]string{
		0: "warn",
		1: "error",
		2: "critical",
	}
	Loglevel_value = map[string]int32{
		"warn":     0,
		"error":    1,
		"critical": 2,
	}
)

func (x Loglevel) Enum() *Loglevel {
	p := new(Loglevel)
	*p = x
	return p
}

func (x Loglevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Loglevel) Descriptor() protoreflect.EnumDescriptor {
	return file_logstore_proto_enumTypes[0].Descriptor()
}

func (Loglevel) Type() protoreflect.EnumType {
	return &file_logstore_proto_enumTypes[0]
}

func (x Loglevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Loglevel.Descriptor instead.
func (Loglevel) EnumDescriptor() ([]byte, []int) {
	return file_logstore_proto_rawDescGZIP(), []int{0}
}

type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Details       string                 `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	Level         Loglevel               `protobuf:"varint,4,opt,name=level,proto3,enum=logstore.Loglevel" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_logstore_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_logstore_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_logstore_proto_rawDescGZIP(), []int{0}
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogEntry) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *LogEntry) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

func (x *LogEntry) GetLevel() Loglevel {
	if x != nil {
		return x.Level
	}
	return Loglevel_warn
}

type LogEntryReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entry         *LogEntry              `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntryReq) Reset() {
	*x = LogEntryReq{}
	mi := &file_logstore_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntryReq) ProtoMessage() {}

func (x *LogEntryReq) ProtoReflect() protoreflect.Message {
	mi := &file_logstore_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntryReq.ProtoReflect.Descriptor instead.
func (*LogEntryReq) Descriptor() ([]byte, []int) {
	return file_logstore_proto_rawDescGZIP(), []int{1}
}

func (x *LogEntryReq) GetEntry() *LogEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

type LogEntryRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inserted      bool                   `protobuf:"varint,1,opt,name=inserted,proto3" json:"inserted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntryRes) Reset() {
	*x = LogEntryRes{}
	mi := &file_logstore_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntryRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntryRes) ProtoMessage() {}

func (x *LogEntryRes) ProtoReflect() protoreflect.Message {
	mi := &file_logstore_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntryRes.ProtoReflect.Descriptor instead.
func (*LogEntryRes) Descriptor() ([]byte, []int) {
	return file_logstore_proto_rawDescGZIP(), []int{2}
}

func (x *LogEntryRes) GetInserted() bool {
	if x != nil {
		return x.Inserted
	}
	return false
}

type Logretrivalreq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	All           bool                   `protobuf:"varint,1,opt,name=all,proto3" json:"all,omitempty"`
	Latest        bool                   `protobuf:"varint,2,opt,name=latest,proto3" json:"latest,omitempty"`
	Head          int32                  `protobuf:"varint,3,opt,name=head,proto3" json:"head,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Logretrivalreq) Reset() {
	*x = Logretrivalreq{}
	mi := &file_logstore_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Logretrivalreq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Logretrivalreq) ProtoMessage() {}

func (x *Logretrivalreq) ProtoReflect() protoreflect.Message {
	mi := &file_logstore_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Logretrivalreq.ProtoReflect.Descriptor instead.
func (*Logretrivalreq) Descriptor() ([]byte, []int) {
	return file_logstore_proto_rawDescGZIP(), []int{3}
}

func (x *Logretrivalreq) GetAll() bool {
	if x != nil {
		return x.All
	}
	return false
}

func (x *Logretrivalreq) GetLatest() bool {
	if x != nil {
		return x.Latest
	}
	return false
}

func (x *Logretrivalreq) GetHead() int32 {
	if x != nil {
		return x.Head
	}
	return 0
}

type ClearRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cleared       bool                   `protobuf:"varint,1,opt,name=cleared,proto3" json:"cleared,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearRes) Reset() {
	*x = ClearRes{}
	mi := &file_logstore_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearRes) ProtoMessage() {}

func (x *ClearRes) ProtoReflect() protoreflect.Message {
	mi := &file_logstore_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearRes.ProtoReflect.Descriptor instead.
func (*ClearRes) Descriptor() ([]byte, []int) {
	return file_logstore_proto_rawDescGZIP(), []int{4}
}

func (x *ClearRes) GetCleared() bool {
	if x != nil {
		return x.Cleared
	}
	return false
}

type ListenReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Loglevel      int32                  `protobuf:"varint,1,opt,name=loglevel,proto3" json:"loglevel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListenReq) Reset() {
	*x = ListenReq{}
	mi := &file_logstore_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListenReq) ProtoMessage() {}

func (x *ListenReq) ProtoReflect() protoreflect.Message {
	mi := &file_logstore_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListenReq.ProtoReflect.Descriptor instead.
func (*ListenReq) Descriptor() ([]byte, []int) {
	return file_logstore_proto_rawDescGZIP(), []int{5}
}

func (x *ListenReq) GetLoglevel() int32 {
	if x != nil {
		return x.Loglevel
	}
	return 0
}

var File_logstore_proto protoreflect.FileDescriptor

const file_logstore_proto_rawDesc = "" +
	"\n" +
	"\x0elogstore.proto\x12\blogstore\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa2\x01\n" +
	"\blogEntry\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x18\n" +
	"\adetails\x18\x03 \x01(\tR\adetails\x12(\n" +
	"\x05level\x18\x04 \x01(\x0e2\x12.logstore.loglevelR\x05level\"7\n" +
	"\vlogEntryReq\x12(\n" +
	"\x05entry\x18\x01 \x01(\v2\x12.logstore.logEntryR\x05entry\")\n" +
	"\vlogEntryRes\x12\x1a\n" +
	"\binserted\x18\x01 \x01(\bR\binserted\"N\n" +
	"\x0elogretrivalreq\x12\x10\n" +
	"\x03all\x18\x01 \x01(\bR\x03all\x12\x16\n" +
	"\x06latest\x18\x02 \x01(\bR\x06latest\x12\x12\n" +
	"\x04head\x18\x03 \x01(\x05R\x04head\"$\n" +
	"\bclearRes\x12\x18\n" +
	"\acleared\x18\x01 \x01(\bR\acleared\"'\n" +
	"\tlistenReq\x12\x1a\n" +
	"\bloglevel\x18\x01 \x01(\x05R\bloglevel*-\n" +
	"\bloglevel\x12\b\n" +
	"\x04warn\x10\x00\x12\t\n" +
	"\x05error\x10\x01\x12\f\n" +
	"\bcritical\x10\x022\xf7\x01\n" +
	"\n" +
	"logservice\x12<\n" +
	"\n" +
	"publishLog\x12\x15.logstore.logEntryReq\x1a\x15.logstore.logEntryRes\"\x00\x12:\n" +
	"\x06getlog\x12\x18.logstore.logretrivalreq\x1a\x12.logstore.logEntry\"\x000\x01\x128\n" +
	"\bclearlog\x12\x16.google.protobuf.Empty\x1a\x12.logstore.clearRes\"\x00\x125\n" +
	"\x06listen\x12\x13.logstore.listenReq\x1a\x12.logstore.logEntry\"\x000\x01B\fZ\n" +
	"./logStoreb\x06proto3"

var (
	file_logstore_proto_rawDescOnce sync.Once
	file_logstore_proto_rawDescData []byte
)

func file_logstore_proto_rawDescGZIP() []byte {
	file_logstore_proto_rawDescOnce.Do(func() {
		file_logstore_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_logstore_proto_rawDesc), len(file_logstore_proto_rawDesc)))
	})
	return file_logstore_proto_rawDescData
}

var file_logstore_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_logstore_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_logstore_proto_goTypes = []any{
	(Loglevel)(0),                 // 0: logstore.loglevel
	(*LogEntry)(nil),              // 1: logstore.logEntry
	(*LogEntryReq)(nil),           // 2: logstore.logEntryReq
	(*LogEntryRes)(nil),           // 3: logstore.logEntryRes
	(*Logretrivalreq)(nil),        // 4: logstore.logretrivalreq
	(*ClearRes)(nil),              // 5: logstore.clearRes
	(*ListenReq)(nil),             // 6: logstore.listenReq
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 8: google.protobuf.Empty
}
var file_logstore_proto_depIdxs = []int32{
	7, // 0: logstore.logEntry.timestamp:type_name -> google.protobuf.Timestamp
	0, // 1: logstore.logEntry.level:type_name -> logstore.loglevel
	1, // 2: logstore.logEntryReq.entry:type_name -> logstore.logEntry
	2, // 3: logstore.logservice.publishLog:input_type -> logstore.logEntryReq
	4, // 4: logstore.logservice.getlog:input_type -> logstore.logretrivalreq
	8, // 5: logstore.logservice.clearlog:input_type -> google.protobuf.Empty
	6, // 6: logstore.logservice.listen:input_type -> logstore.listenReq
	3, // 7: logstore.logservice.publishLog:output_type -> logstore.logEntryRes
	1, // 8: logstore.logservice.getlog:output_type -> logstore.logEntry
	5, // 9: logstore.logservice.clearlog:output_type -> logstore.clearRes
	1, // 10: logstore.logservice.listen:output_type -> logstore.logEntry
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_logstore_proto_init() }
func file_logstore_proto_init() {
	if File_logstore_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_logstore_proto_rawDesc), len(file_logstore_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_logstore_proto_goTypes,
		DependencyIndexes: file_logstore_proto_depIdxs,
		EnumInfos:         file_logstore_proto_enumTypes,
		MessageInfos:      file_logstore_proto_msgTypes,
	}.Build()
	File_logstore_proto = out.File
	file_logstore_proto_goTypes = nil
	file_logstore_proto_depIdxs = nil
}
